name: Multi-Repo Snake Pattern for ADITHYAN B RAJ

on:
  workflow_dispatch:
    inputs:
      create_repos:
        description: 'Create letter pattern repositories'
        required: true
        default: 'true'
        type: boolean

permissions:
  contents: write

jobs:
  create-pattern-repos:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_repos == 'true' }}
    
    steps:
      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
      - name: Create repositories for ADITHYAN B RAJ pattern
        run: |
          # Function to create repo with commits
          create_pattern_repo() {
            local repo_name=$1
            local letter=$2
            local position=$3
            
            echo "Creating repository: $repo_name for letter $letter at position $position"
            
            # Create repository
            gh repo create "$repo_name" --private --description "Pattern pixel for letter $letter - ADITHYAN B RAJ snake animation"
            
            # Clone and add commits
            git clone "https://github.com/${{ github.repository_owner }}/$repo_name.git"
            cd "$repo_name"
            
            # Configure git
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            
            # Create README
            echo "# $letter - Position $position" > README.md
            echo "This repository is part of the ADITHYAN B RAJ snake animation pattern." >> README.md
            echo "Letter: **$letter** | Position: $position" >> README.md
            
            git add README.md
            git commit -m "Initial commit for letter $letter pattern"
            
            # Create multiple commits to ensure visibility on contribution graph
            for i in {1..5}; do
              echo "Commit $i for pattern visibility" >> commits.txt
              git add commits.txt
              git commit -m "Pattern commit $i for $letter"
            done
            
            git push
            cd ..
            rm -rf "$repo_name"
            
            sleep 2  # Rate limiting
          }
          
          # Letter A (positions 1-8)
          create_pattern_repo "A1-top-left" "A" "1"
          create_pattern_repo "A2-top-center" "A" "2" 
          create_pattern_repo "A3-top-right" "A" "3"
          create_pattern_repo "A4-middle-left" "A" "4"
          create_pattern_repo "A5-middle-center" "A" "5"
          create_pattern_repo "A6-middle-right" "A" "6"
          create_pattern_repo "A7-bottom-left" "A" "7"
          create_pattern_repo "A8-bottom-right" "A" "8"
          
          # Letter D (positions 1-10)
          create_pattern_repo "D1-left-top" "D" "1"
          create_pattern_repo "D2-left-upper" "D" "2"
          create_pattern_repo "D3-left-middle" "D" "3"
          create_pattern_repo "D4-left-lower" "D" "4"
          create_pattern_repo "D5-left-bottom" "D" "5"
          create_pattern_repo "D6-top-center" "D" "6"
          create_pattern_repo "D7-top-right" "D" "7"
          create_pattern_repo "D8-right-middle" "D" "8"
          create_pattern_repo "D9-bottom-center" "D" "9"
          create_pattern_repo "D10-bottom-right" "D" "10"
          
          # Letter I (positions 1-7)
          create_pattern_repo "I1-top-left" "I" "1"
          create_pattern_repo "I2-top-center" "I" "2"
          create_pattern_repo "I3-top-right" "I" "3"
          create_pattern_repo "I4-middle-center" "I" "4"
          create_pattern_repo "I5-bottom-left" "I" "5"
          create_pattern_repo "I6-bottom-center" "I" "6"
          create_pattern_repo "I7-bottom-right" "I" "7"
          
          # Letter T (positions 1-6)
          create_pattern_repo "T1-top-left" "T" "1"
          create_pattern_repo "T2-top-center" "T" "2"
          create_pattern_repo "T3-top-right" "T" "3"
          create_pattern_repo "T4-middle-center" "T" "4"
          create_pattern_repo "T5-lower-center" "T" "5"
          create_pattern_repo "T6-bottom-center" "T" "6"
          
          # Letter H (positions 1-10)
          create_pattern_repo "H1-left-top" "H" "1"
          create_pattern_repo "H2-left-upper" "H" "2"
          create_pattern_repo "H3-left-middle" "H" "3"
          create_pattern_repo "H4-left-lower" "H" "4"
          create_pattern_repo "H5-left-bottom" "H" "5"
          create_pattern_repo "H6-middle-center" "H" "6"
          create_pattern_repo "H7-right-top" "H" "7"
          create_pattern_repo "H8-right-upper" "H" "8"
          create_pattern_repo "H9-right-lower" "H" "9"
          create_pattern_repo "H10-right-bottom" "H" "10"
          
          # Letter Y (positions 1-7)
          create_pattern_repo "Y1-top-left" "Y" "1"
          create_pattern_repo "Y2-top-right" "Y" "2"
          create_pattern_repo "Y3-upper-center" "Y" "3"
          create_pattern_repo "Y4-middle-center" "Y" "4"
          create_pattern_repo "Y5-lower-center" "Y" "5"
          create_pattern_repo "Y6-bottom-center" "Y" "6"
          
          # Letter A (second A - positions 1-8)
          create_pattern_repo "A2-1-top-left" "A" "1"
          create_pattern_repo "A2-2-top-center" "A" "2"
          create_pattern_repo "A2-3-top-right" "A" "3"
          create_pattern_repo "A2-4-middle-left" "A" "4"
          create_pattern_repo "A2-5-middle-center" "A" "5"
          create_pattern_repo "A2-6-middle-right" "A" "6"
          create_pattern_repo "A2-7-bottom-left" "A" "7"
          create_pattern_repo "A2-8-bottom-right" "A" "8"
          
          # Letter N (positions 1-10)
          create_pattern_repo "N1-left-top" "N" "1"
          create_pattern_repo "N2-left-upper" "N" "2"
          create_pattern_repo "N3-left-middle" "N" "3"
          create_pattern_repo "N4-left-lower" "N" "4"
          create_pattern_repo "N5-left-bottom" "N" "5"
          create_pattern_repo "N6-diagonal-1" "N" "6"
          create_pattern_repo "N7-diagonal-2" "N" "7"
          create_pattern_repo "N8-right-top" "N" "8"
          create_pattern_repo "N9-right-middle" "N" "9"
          create_pattern_repo "N10-right-bottom" "N" "10"
          
          # SPACE (no repos for space)
          
          # Letter B (positions 1-12)
          create_pattern_repo "B1-left-top" "B" "1"
          create_pattern_repo "B2-left-upper" "B" "2"
          create_pattern_repo "B3-left-middle" "B" "3"
          create_pattern_repo "B4-left-lower" "B" "4"
          create_pattern_repo "B5-left-bottom" "B" "5"
          create_pattern_repo "B6-top-center" "B" "6"
          create_pattern_repo "B7-top-right" "B" "7"
          create_pattern_repo "B8-middle-center" "B" "8"
          create_pattern_repo "B9-middle-right" "B" "9"
          create_pattern_repo "B10-bottom-center" "B" "10"
          create_pattern_repo "B11-bottom-right" "B" "11"
          
          # SPACE (no repos for space)
          
          # Letter R (positions 1-11)
          create_pattern_repo "R1-left-top" "R" "1"
          create_pattern_repo "R2-left-upper" "R" "2"
          create_pattern_repo "R3-left-middle" "R" "3"
          create_pattern_repo "R4-left-lower" "R" "4"
          create_pattern_repo "R5-left-bottom" "R" "5"
          create_pattern_repo "R6-top-center" "R" "6"
          create_pattern_repo "R7-top-right" "R" "7"
          create_pattern_repo "R8-middle-center" "R" "8"
          create_pattern_repo "R9-diagonal" "R" "9"
          create_pattern_repo "R10-bottom-right" "R" "10"
          
          # Letter A (third A - positions 1-8)
          create_pattern_repo "A3-1-top-left" "A" "1"
          create_pattern_repo "A3-2-top-center" "A" "2"
          create_pattern_repo "A3-3-top-right" "A" "3"
          create_pattern_repo "A3-4-middle-left" "A" "4"
          create_pattern_repo "A3-5-middle-center" "A" "5"
          create_pattern_repo "A3-6-middle-right" "A" "6"
          create_pattern_repo "A3-7-bottom-left" "A" "7"
          create_pattern_repo "A3-8-bottom-right" "A" "8"
          
          # Letter J (positions 1-7)
          create_pattern_repo "J1-top-left" "J" "1"
          create_pattern_repo "J2-top-center" "J" "2"
          create_pattern_repo "J3-top-right" "J" "3"
          create_pattern_repo "J4-middle-right" "J" "4"
          create_pattern_repo "J5-lower-right" "J" "5"
          create_pattern_repo "J6-bottom-center" "J" "6"
          create_pattern_repo "J7-bottom-left" "J" "7"
          
          echo "✅ All repositories created successfully!"
          echo "Total repositories created: ~90 (representing each pixel of ADITHYAN B RAJ)"

  generate-snake:
    runs-on: ubuntu-latest
    needs: create-pattern-repos
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Wait for repositories to be indexed
        run: |
          echo "Waiting 60 seconds for GitHub to index new repositories..."
          sleep 60
          
      - name: Generate snake eating the pattern
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/multi-repo-snake.svg
            dist/multi-repo-snake-dark.svg?palette=github-dark&background_color=0d1117
            dist/multi-repo-snake-neon.svg?palette=github-neon
            dist/multi-repo-snake.gif?color_snake=#ff0000&color_dots=#39d353,#26a641,#006d32,#0d4017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate contribution overview
        run: |
          mkdir -p dist
          
          # Create summary file
          cat > dist/pattern-summary.md << 'EOF'
          # ADITHYAN B RAJ Snake Pattern
          
          This snake animation is generated from ~90 micro-repositories, each representing a pixel in the letter pattern.
          
          ## Pattern Breakdown:
          - **A**: 8 repositories (A1-A8)
          - **D**: 10 repositories (D1-D10)  
          - **I**: 7 repositories (I1-I7)
          - **T**: 6 repositories (T1-T6)
          - **H**: 10 repositories (H1-H10)
          - **Y**: 6 repositories (Y1-Y6)
          - **A**: 8 repositories (A2-1 to A2-8)
          - **N**: 10 repositories (N1-N10)
          - **B**: 11 repositories (B1-B11)
          - **R**: 10 repositories (R1-R10)
          - **A**: 8 repositories (A3-1 to A3-8)
          - **J**: 7 repositories (J1-J7)
          
          Each repository contains commits that make it appear on the GitHub contribution graph, forming the letters that the snake will eat!
          EOF
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output

  cleanup-repos:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_repos == 'false' }}
    
    steps:
      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
      - name: Delete pattern repositories (optional cleanup)
        run: |
          echo "This job can be used to clean up the pattern repositories if needed"
          echo "Uncomment the lines below to delete all pattern repos"
          
          # WARNING: This will delete all pattern repositories!
          # gh repo delete A1-top-left --confirm
          # gh repo delete A2-top-center --confirm
          # ... (continue for all repos)
          
          echo "Cleanup not executed - uncomment lines in workflow to enable"
